// Generated by scripts/build-scan.mjs from visually reviewed source.
window.OPIC_SCAN = {
  "additions": [
    {
      "id": "change-questions",
      "page": 2,
      "title": "과거·현재 비교 2 · 질문",
      "section": "answers/change",
      "questions": [
        "How have the ways people buy groceries changed over the years? Where did people buy food in the past, and how do they buy it now?",
        "Banks have changed over the years. How do banks look different than they did in the past? What kinds of changes are the most evident? What kind of impact have these changes had on the customers? Give me all the details.",
        "How is the phone you use today different from the ones you used in the past? What kind of difference do phones make in your life? Give me details.",
        "How is recycling today different from when you were young? Are there any big differences? Are there any similarities? Tell me about how recycling has changed over the years.",
        "Ideas about what good health is and how to maintain it change frequently. What did people do to maintain good health when you were a child? What was considered to be a healthy diet at that time? How did people usually exercise? Describe how our ideas of what is healthy have changed over time."
      ],
      "text": ""
    },
    {
      "id": "change-frame",
      "page": 2,
      "title": "과거·현재 비교 2 · 문장 틀",
      "section": "answers/change",
      "questions": [],
      "text": "Um... let me see... I’m not familiar with the subject, but... Personally, I believe that the ... has/have changed noticeably.\nIn the past, ...ing was/were the most common.\nI mean, ...\nHowever, unlike the past, ... considerably nowadays.\nThis has led people to ... and even ...",
      "kind": "template"
    },
    {
      "id": "grocery-notes",
      "page": 2,
      "title": "식료품 구매 변화 · 필기",
      "section": "answers/change",
      "questions": [],
      "text": "과거\ngoing to the grocery store and buy my food\nIt was time-consuming and geographical limits existed\n현재\ntechnology has(been) developed\nshop online\ntheir purchases are delivered on the same day they order",
      "kind": "template"
    },
    {
      "id": "social-frame",
      "page": 3,
      "title": "사회 이슈 · 문장 틀",
      "section": "answers/issue",
      "questions": [],
      "text": "Well... Actually, it’s not easy to remember an issue regarding ..., because I’m a person who is not interested in/closely related to ... Let me think... Well...\nOne of the memorable articles I read was ... caused by ...\n... and this led people to ...\nUnfortunately, several people ended up ...ing, so the government gave the public a warning/recommendation to ...",
      "kind": "template"
    },
    {
      "id": "place-frames",
      "page": 4,
      "title": "장소 묘사 1·2 · 문장 틀",
      "section": "answers/place",
      "questions": [],
      "text": "장소 묘사 1\nWhen it comes to the ..., it’s called ... which is located in ...\nAs for the striking feature, it ... compared to others.\nAnd, there are ... as well.\nFor these reasons it swarms with ... all through the year.\nA few ... ago, I went there and ... and it was much more ... than I thought!\nThis is the ... that I ...\n\n장소 묘사 2\nRegarding the ..., it is ... situated in ... and has ...\nThis is vital for someone who ... like me.\nPlus, I can see ...\nLast but not least, the main reason I prefer ... is the walking distance, which takes just 10 minutes to get there on foot.",
      "kind": "template"
    },
    {
      "id": "activities-frames",
      "page": 7,
      "title": "활동 묘사 · 전후·순서·준비",
      "section": "answers/activity",
      "questions": [
        "What activities do you normally do before and after the movie? Tell me about your typical movie day form the beginning to the end.",
        "Can you tell me what you usually do at the park? Describe your typical day at a park from the beginning to the end.",
        "Can you tell me all the things you do in order to prepare to take trips?"
      ],
      "text": "전후 활동\nWell... as one of my hobbies is ..., I try to ... as much as possible. I reckon I do various things before and after ...\nBefore ..., I ...\nAfter ..., ing and ing are the ones I always do.\nWell... last ..., I ...\nThese are the activities that I do before and after ...\n\n처음부터 끝까지\nWell... as one of my hobbies is ..., I try to ... as much as possible. I reckon I do various things while/when ...\nAs soon as I get to ..., I ...\nAfter that, ing and ing are the ones I always do.\nWell... last ..., I ...\nThese are the ... that I do while/when ...\n\n여행 준비\nWell... as one of my hobbies is ..., I try to ... as much as possible. I reckon I do various things to ...\nAbove all, I ...\nIn addition, ing and ing are the ones I always do.\nWell... last ..., I ... / Last but not least, I ...\nThese are the ... that I ...",
      "kind": "template"
    },
    {
      "id": "activities-health",
      "page": 8,
      "title": "건강 유지 · 문장 틀",
      "section": "answers/activity",
      "questions": [
        "Tell me about all the things that you do in order to stay healthy."
      ],
      "text": "I reckon I do various things to ...\nAbove all, I ...\nIn addition, ing and ing are the ones I always do.\nLast but not least, I ...\nThese are the ... that ...",
      "kind": "template"
    },
    {
      "id": "activities-seasons",
      "page": 8,
      "title": "계절별 여가 활동 · 문장 틀",
      "section": "answers/activity",
      "questions": [
        "Tell me about the outdoor activities that are popular in your country. Do people go hiking, bike or swim? What people typically do outdoors? / Please tell me about what kinds of free time activities people in your country do.",
        "What do people in your country like to do in their free time? What are some popular free-time activities?"
      ],
      "text": "I reckon ... do various things ...\nIn Spring, ...\nMoreover, ing and ing are popular in Summer.\nWhen fall comes, ...\nLastly, ing and ing are loved in Winter.\nThese are the ... that ...",
      "kind": "template"
    },
    {
      "id": "housework-frame",
      "page": 8,
      "title": "집안일 · 문장 틀",
      "section": "answers/activity",
      "questions": [
        "Tell me what you do to keep your house clean and comfortable. What kinds of housework do you do around your home?",
        "What is your normal routine at home? What do you usually do during the weekdays? What kinds of things do you do on the weekend?"
      ],
      "text": "I reckon I do various ...\nI ... on weekdays. In fact, I am a person who is kind of a neat/clean freak.\nOn weekends, I spend a great deal of time catching up on the household chores. ing and ing are the ones I always do. I think housework is never-ending.\nThese are the household chores that I usually do.",
      "kind": "template"
    },
    {
      "id": "detail-questions",
      "page": 9,
      "title": "세부사항 · 질문과 구성",
      "section": "answers/detail",
      "questions": [
        "What genre of movie do you like to watch? How often do you watch a movie? Where do you like to watch a movie? What activities do you do before and after watching movies?",
        "Tell me a little bit about a country close to your own country. Tell me what the country looks like, about its people and some of its traditions."
      ],
      "text": "영화: What genre → How often → Where\n이웃 국가: country → people → traditions\n각 항목: 메인 답변 + 부연설명",
      "kind": "template"
    },
    {
      "id": "compare-music",
      "page": 10,
      "title": "음악·가수·작곡가 비교 · 질문",
      "section": "answers/compare",
      "questions": [
        "Pick two different kinds of music or composers. Describe each in as much detail as possible, and then compare the similarities and differences between them.",
        "Select two different types of singers or composers. Tell me about both of these with a lot of details. Compare these with regard to their similarities and differences."
      ],
      "text": ""
    },
    {
      "id": "compare-frame",
      "page": 10,
      "title": "비교·대조 · 문장 틀",
      "section": "answers/compare",
      "questions": [],
      "text": "Well... There are/is ... I could talk about, but now I compare ...\nBoth of them ..., but they are somewhat different in many ways.\nAs for ..., ...\nIn terms of ..., ...\nI believe even though their characteristics are slightly similar, they ...\nThese are the similarities and differences between ...",
      "kind": "template"
    },
    {
      "id": "reason-questions",
      "page": 12,
      "title": "이유 말하기 · 질문과 문장 틀",
      "section": "answers/reason",
      "questions": [
        "What was a memorable movie you watched in the past? What was it about? What was special about that movie? Would you recommend that movie to other people?",
        "Many people try to eat healthy these days. What kinds of foods are healthy and why are they healthy for us?",
        "Where do people in your country go to when they travel abroad? Why do they like visiting those locations? What is special about the countries they visit?",
        "What are some of the companies that young people want to work for these days? Why do young people want to work for these companies?"
      ],
      "text": "Well... as for ..., it is ... and there are some reasons ...\nOne of the main reasons is N / that ... + 부연설명\nAnother reason is N / that ... + 부연설명\nThese are the reasons ...",
      "kind": "template"
    },
    {
      "id": "reason-expressions",
      "page": 11,
      "title": "이유를 설명하는 표현",
      "section": "expressions/reasons",
      "questions": [],
      "text": "cheer up → 기분을 좋게 하다\ntake comfort → 위안을 받다\nkill the time → 시간을 때우다\nhelp me concentrate on studying → 공부에 집중할 수 있게 도와주다\ncan empathize with the lyrics → 가사에 공감할 수 있다\nrelieve boredom → 무료함을 달래다",
      "kind": "expressions"
    },
    {
      "id": "travel-phone",
      "page": 14,
      "title": "국내여행 준비물 · 스마트폰",
      "section": "scripts/object",
      "questions": [],
      "text": "The thing I always take is a smart phone which has hundreds of functions. There’s no doubt that it’s a recently released and the best-selling item nowadays. With regard to the features, it is well known for its high quality and coming in various colours. So, it’s loved by most women who are sensitive to the trend. Most importantly, it has an AI function. It’s quite practical.",
      "kind": "script",
      "target": 1002,
      "cues": [
        "스마트폰 · 수백 가지 기능",
        "최근 출시 · 인기 제품",
        "품질 · 색상",
        "AI 기능"
      ]
    },
    {
      "id": "movie-device-opening",
      "page": 14,
      "title": "영화 기기 · 시작 문장",
      "section": "scripts/object",
      "questions": [],
      "text": "Well... The latest electronic equipment I use when I watch movies is a smart phone...",
      "kind": "opening",
      "target": 1003
    },
    {
      "id": "music-device-opening",
      "page": 14,
      "title": "음악 기기 · 시작 문장",
      "section": "scripts/object",
      "questions": [],
      "text": "Well... The latest electronic equipment that music fans are interested in is a smart phone...",
      "kind": "opening",
      "target": 1004
    },
    {
      "id": "hiking-clothes",
      "page": 14,
      "title": "하이킹 복장과 준비물",
      "section": "scripts/object",
      "questions": [],
      "text": "Well... The clothing I usually wear is a sweatsuit which is breathable and machine-washable. There’s no doubt that it’s a recently released and the best-selling item nowadays. With regard to the features, it is well known for its high quality and coming in various colours. So, it’s loved by most women who are sensitive to the trend. Most importantly, it uses/is made of functional material. It’s quite practical. Oh, I also make sure to bring a bottle of water, a roll of gimbap, a small towel, and my phone and earphones so I don’t get bored.",
      "kind": "script",
      "target": 1007,
      "cues": [
        "통기성 · 세탁 가능한 운동복",
        "최근 출시 · 품질 · 색상",
        "기능성 소재",
        "물 · 김밥 · 수건 · 휴대전화 · 이어폰"
      ]
    },
    {
      "id": "eva-frame",
      "page": 15,
      "title": "에바에게 질문하기 · 문장 틀",
      "section": "answers/roleplay",
      "questions": [],
      "text": "I am glad to hear that ... / You told me that ... / I heard that ...\nIf you don’t mind, I’d like to ask a few questions about ... / I want to ask you about ...\nFirst of all, could you tell me ...? + 부연설명\nSecond of all, I was wondering about/if ... + 부연설명\nLastly, I’d like to know about ... + 부연설명\nThank you for your kind answers. / Thank you so much for your time.",
      "kind": "template"
    },
    {
      "id": "reservation-frame",
      "page": 15,
      "title": "예약·문의 · 문장 틀",
      "section": "answers/roleplay",
      "questions": [],
      "text": "Hello, I’m calling to book/make an appointment/get some information about ... and I have some questions (I’d like to ask).\nFirst of all, could you tell me ...? + 부연설명\nSecond of all, I was wondering about/if ... + 부연설명\nLastly, I’d like to know ... 부연설명\nThank you so much for your time. / Thank you so much for your help. Bye!",
      "kind": "template"
    },
    {
      "id": "solution-frame",
      "page": 16,
      "title": "문제 해결 · 문장 틀",
      "section": "answers/roleplay",
      "questions": [],
      "text": "Actually, I have some bad news. / I have something to tell you.\nAs you know, 상황설명\nI’m terribly sorry, and I would like to give you some options.\nFirstly, how about ing ...? + 부연설명\nSecondly, do you want me to ... you’ve always wanted? + 부연설명\nOr, why don’t I/we...? + 부연설명\nI am really sorry once again. Please let me know what you think.\nI feel so bad, and I will do anything for you. Don’t hesitate to tell me what you want. Bye!\nThank you for your understanding. Please let me know what I can do.",
      "kind": "template"
    },
    {
      "id": "travel-checklist",
      "page": 18,
      "title": "해외여행 · 18유형 점검",
      "section": "scripts/travel",
      "questions": [],
      "text": "1. 자주 가는 해외여행지를 묘사해 보세요. [장소묘사 1]\n2. 최근 갔던 해외여행지를 묘사해 보세요. [장소묘사 2]\n3. 해외여행에 관심을 가지게 된 계기는 무엇인가요. [계기말하기]\n4. 해외여행 가는 이유에 대해 말해주세요. [이유말하기]\n5. 해외여행 갈 때 함께 하는 인물에 대해 묘사해 주세요. [인물묘사]\n6. 해외여행 갈 때 꼭 가져가는 물품에 대해 말해주세요. [사물묘사] · 필기: power bank\n7. 처음으로 해외여행 갔을 때 있었던 경험에 대해 말해주세요. [경험 1]\n8. 가장 최근 해외여행 갔던 경험에 대해 말해주세요. [경험 2]\n9. 해외여행 가서 기억남는 경험을 말해주세요. [경험 3]\n10. 당신이 자주 가는 해외여행지는 과거와 비교하여 현재 어떻게 달라졌나요. [과거현재비교]\n11. 당신이 해외여행 가서 하는 전형적 일과를 설명해 보세요. [활동묘사]\n12. 당신이 해외여행 가기전 준비하는 것들에 대해 말해주세요. [활동묘사]\n13. 당신의 나라와 근래 여행 했던 나라를 비교 대조해 보세요. [비교대조]\n14. 당신은 누구와, 언제, 얼마나 자주, 왜 해외여행을 가는지 말해주세요. [세부사항]\n15. 여행 가는 사람들이 자주 언급하는 이슈는 무엇인가요? 그 문제 해결을 위해 어떤 대처가 취해지고 있나요? [사회이슈]\n16. 공항에서 항공편이 2시간 출발 지연되어 카운터에 문의. [에바질문]\n17. 항공편 지연으로 고객 미팅에 못가게 되어 전화로 설명하고 대안제시. [문제해결]\n18. 본인이 여행 중 어려움이 생겼던 경험이 있나요? 자세히 말해주세요. [롤플레이 경험]",
      "kind": "checklist"
    },
    {
      "id": "hiking-change",
      "page": 1,
      "title": "하이킹 패턴 · 과거와 현재",
      "section": "scripts/change",
      "questions": [
        "As compared with past time, do people in your country go hiking more or less frequently? How has the pattern of hiking changed over the years?"
      ],
      "text": "Looking back over the past 15 years, the pattern of hiking has changed significantly over the past several years. Almost every person spent much time working, and I also used to work only. On the other hand, most people now enjoy various free-time activities such as snowboarding, fishing, playing golf, hiking, and so on. Well... Last week, I went hiking with my family to spend quality time, and it was a pleasant moment for us. It’s a big difference, because people used to have a limited type of activity before.",
      "kind": "script",
      "cues": [
        "과거 15년 · 일만 함",
        "현재 · 다양한 여가 활동",
        "지난주 가족과 하이킹",
        "활동 선택의 변화"
      ]
    },
    {
      "id": "recycling-fine",
      "page": 6,
      "title": "재활용 중 벌금을 낸 경험",
      "section": "scripts/experience",
      "questions": [
        "Problems sometimes occur while recycling. Perhaps, the pick-up service did not come as planned. Or, the items were too big for the containers. Or, the container turned over and spilled the items. Tell me about something memorable that happened to you or your family."
      ],
      "text": "Um... actually, there are several stories related to recycling. Well... it happened when the law first changed. Sorting out the garbage was unfamiliar and annoying to me. One day, I went outside and threw away all the recyclables without separating them. A few days later, I got a ticket/a ticket showed up. It turned out that the resident next to me was actually a government officer in charge of recycling/it turned out that the resident reported it. As a result, a fine was unavoidable/I paid a fine. Since then, I’ve been very careful about separating my trash properly.",
      "kind": "script",
      "cues": [
        "법이 바뀌었을 때",
        "분리하지 않고 버림",
        "이웃 · 신고 · 벌금",
        "분리수거에 주의"
      ]
    },
    {
      "id": "jogging-details",
      "page": 9,
      "title": "조깅 · 빈도·장소·동행",
      "section": "scripts/detail",
      "questions": [
        "How often do you jog? Where do you usually jog? Who do you jog with? Why do you jog?"
      ],
      "text": "Well... it’s been over 5 years since I first started to jog. To be specific, I try to jog on a regular basis because regular exercise is one of the best ways to clear the head. Moreover, I jog at Dongtan park which is next to my house. The reason I like the park is that a variety of sports equipment, courts, a huge track, and water fountains are well-equipped. Turning to the person I jog with, he is my brother who is 2 years older than me as we both have been interested in running. These are the details of how I jog.",
      "kind": "script",
      "cues": [
        "5년 넘게 조깅",
        "규칙적 운동 · 머리를 식힘",
        "집 옆 동탄 공원 · 시설",
        "두 살 많은 형과 함께"
      ]
    },
    {
      "id": "music-reasons",
      "page": 11,
      "title": "음악을 듣는 이유",
      "section": "scripts/reason",
      "questions": [
        "You indicated you enjoy listening to music. Why do you like listening to music?"
      ],
      "text": "Well... As for listening to music, there are some reasons why I enjoy it. One of the main reasons is that it’s the best way to relieve the massive pressure that I get from work. Yesterday, because of a mistake caused by my carelessness, I was reprimanded by my superior, and it made me feel blue. So, on my way home after leaving work, I listened to up-tempo music, and it cheered me up. Another reason is that it’s apparent it helps me not only feel relaxed but also ease my mind. These are the reasons why I listen to music.",
      "kind": "script",
      "cues": [
        "직장 스트레스 해소",
        "부주의한 실수 · 상사의 질책",
        "퇴근길 빠른 음악 · 기분 전환",
        "긴장 완화 · 마음의 안정"
      ]
    }
  ],
  "roleplaySets": [
    {
      "id": "eva",
      "page": 15,
      "title": "에바에게 질문하기",
      "questions": [
        "I also enjoy jogging. Please ask me three or four questions about the place I go jogging.",
        "I like to eat out at restaurants, too. Please ask me three questions about my favorite restaurants.",
        "I am living in the United Stated of America. Ask me four questions to get to know about my home.",
        "I also enjoy watching movies. Ask me three or four questions about the types of movies I like to watch.",
        "I am a pianist in an orchestra. To learn more about my piano playing, ask me three of four questions.",
        "Ask me four questions about the specific locations where I enjoy walking."
      ],
      "stages": [
        "조깅 장소",
        "음식점",
        "집",
        "영화 · PDF 19쪽",
        "피아노 · PDF 19쪽",
        "걷는 장소 · PDF 19쪽"
      ]
    },
    {
      "id": "booking",
      "page": 15,
      "title": "영화·항공·호텔 예약",
      "questions": [
        "You and your friend will see a movie this Saturday. Call a box office and book movie tickets for both of you.",
        "You’re going to travel abroad next week. Please call the airline and book a flight ticket.",
        "You have to go on a business trip to the States but you have not booked a room. Call a hotel in the states and reserve a room."
      ],
      "stages": [
        "영화 예약",
        "항공권 예약",
        "호텔 예약"
      ]
    },
    {
      "id": "cancel-outing",
      "page": 16,
      "title": "공연·해변 일정 변경",
      "questions": [
        "You bought the concert tickets for today but at the last minute you are so sick that you can’t even get out of bed. Call your friend, explain your situation and give two or three alternatives to your friend.",
        "You have just found out that the weather at the beach you were planning to go to is not going to be good this coming weekend. Call your friend, tell him or her about the weather and give two to three alternatives."
      ],
      "stages": [
        "공연에 갈 수 없는 상황",
        "해변 날씨 문제"
      ]
    },
    {
      "id": "movie-tickets",
      "page": 19,
      "title": "영화 예매 · 잘못된 표",
      "questions": [
        "You want to see a movie with a friend. Contact the movie theatre and ask three or four questions to get the information that you need to purchase movie tickets.",
        "I’m sorry, but there is a problem which I need you to resolve. When you and your friend arrive at the theatre, you discover that they’ve sold the wrong tickets to you. Explain the situation to the ticket seller at the booth. Offer two or three alternatives to solve the problem."
      ],
      "stages": []
    },
    {
      "id": "jogging",
      "page": 19,
      "title": "조깅 약속 · 취소",
      "questions": [
        "A friend asks you to go jogging. Ask your friend three or four questions about his or her plans.",
        "Unfortunately, you just found out that you will be unable to join your friend as you had planned. Contact your friend and explain why you will not be able to join him or her. Then, provide two or three options to solve this issue."
      ],
      "stages": []
    },
    {
      "id": "walking",
      "page": 19,
      "title": "걷기 중 더 걸을 수 없는 상황",
      "questions": [
        "As you are walking, your friend says that he or she wants to walk further, but you cannot. Tell your friend why you are unable to walk any more. Give him or her suggestion as to what to do next."
      ],
      "stages": [
        "문제 해결하기"
      ]
    },
    {
      "id": "flight-cancelled",
      "page": 19,
      "title": "항공편 취소 · 대체편 매진",
      "questions": [
        "Upon arriving at the airport, you are informed that your flight has been cancelled and that there are no other flights available because they are all booked. Contact your travel agency, discuss this situation, and suggest some possible resolutions to this predicament."
      ],
      "stages": [
        "문제 해결하기"
      ]
    },
    {
      "id": "clothes-defect",
      "page": 20,
      "title": "옷 구매 · 불량",
      "questions": [
        "I’d like to give you a situation and ask you to act it out. You are at a clothing store and need to get some clothes. Ask two to three questions about the clothes you would like to buy.",
        "I’m sorry, but there is a problem which I need you to resolve. The clothes you have ordered have arrived, but one of the shirts has a problem. Call the clothing store and explain the problem. Give two to three alternatives to solve the problem.",
        "That’s the end of the situation. Have you ever been unhappy with something that you bought or some service you received? What was the problem? How did you deal with the situation? Tell me everything in detail."
      ],
      "stages": []
    },
    {
      "id": "clothes-wrong",
      "page": 20,
      "title": "옷 구매 · 다른 셔츠 배송",
      "questions": [
        "I’d like to give you a situation and ask you to act it out. You need to buy some clothes. Go to a clothing store and tell me salesperson about the piece of clothing you want to buy. Ask two to three questions about all the things you need to know about that type of clothing.",
        "I’m sorry, but there is a problem which I need you to resolve. The clothes you have ordered arrived at your home, but one of the shirts is not the correct one. Call the clothing store and explain the problem. Make two to three suggestions as to how and when you can get the correct shirt.",
        "That’s the end of the situation. Have you ever bought a piece of clothing and found out that there was a problem with it? Perhaps, there was a rip or a stain on the clothing. Tell me what the problem was and what you did to solve the situation."
      ],
      "stages": []
    },
    {
      "id": "sale-damage",
      "page": 20,
      "title": "세일 문의 · 제품 파손",
      "questions": [
        "I’d like to give you a situation and ask you to act it out. You see a sign at your favorite store that says they’re having a big sale. Go to the store and ask three or four questions to get as much information as possible about the sale.",
        "I’m sorry, but there is a problem which I need you to resolve. Once you get home with an item you bought, you realize that the item is damaged. Call the store and explain the situation and state what you want to do to resolve the situation.",
        "That’s the end of the situation. Have you ever bought something that did not work or was damaged? Tell me about the item you bought that did not function properly or was damaged. Explain what the item was, what was wrong and what you did to resolve the situation."
      ],
      "stages": []
    },
    {
      "id": "sale-price",
      "page": 20,
      "title": "세일 문의 · 할인 미적용",
      "questions": [
        "I’d like to give you a situation and ask you to act it out. You see a sign at your favorite store that says they’re having a big sale. Call the store and ask three or four questions about that special sale.",
        "I’m sorry, but there is a problem which I need you to resolve. Once you get home with the things you bought, you realize that you did not get them at the sale price. Call the store and explain the situation and offer several ways to resolve the situation.",
        "That’s the end of the situation. Have you ever had a problem while you were shopping? Perhaps, a store did not have an item you wanted. Or perhaps, something was too expensive. Tell me about that problem in detail and what you did to deal with the situation."
      ],
      "stages": [
        "질문하기",
        "문제 해결하기",
        "관련 경험 · PDF 21쪽"
      ]
    },
    {
      "id": "sale-missing",
      "page": 21,
      "title": "친구에게 세일 문의 · 물품 누락",
      "questions": [
        "I’d like to give you a situation and ask you to act it out. Your friend tells you about a great sale happening at one of your favorite stores. Ask your friend three or four questions to find out as much as you can about the sale.",
        "I’m sorry, but there is a problem which I need you to resolve. You went to the sale and bought several items. But when you returned home, you are surprised to discover that on item is missing. Call the store and leave a message explaining your problem with as much detail as possible. Suggest several solutions to the situation.",
        "That’s the end of the situation. I’d like to now know about your shopping experience that was particularly memorable. It might have been about a special gift you bought. Or perhaps, it was an interesting experience with a salesperson or even a problem with the purchase. Can you talk about that memorable experience? Describe the circumstances, the items you bought, and how things turned out in the end."
      ],
      "stages": []
    },
    {
      "id": "food-store",
      "page": 21,
      "title": "식료품점 문의 · 물품 누락",
      "questions": [
        "your friend has told you about a great food store. Call your friend and ask two or three questions about the food store he talked about.",
        "A new food store has opened in your neighbourhood. You visited that store and purchased some items. However, when you got home, you found out that the clerk left out some items from your food cart. Call the store, explain the situation and make suggestions to solve the problem.",
        "Tell me about how you found a food store. Where is it located and why do you like going there? What do you like to shop for there? Give me all the details about that food store you go to."
      ],
      "stages": []
    },
    {
      "id": "travel-dates",
      "page": 22,
      "title": "여행 일정 예약 불가",
      "questions": [
        "I’m sorry, but there is a problem which I need you to resolve. The travel agent informs you that the vacation you want is not available for the dates you want. Call your friend, leave a message explaining the situation and offer two or three alternatives."
      ],
      "stages": [
        "문제 해결하기"
      ]
    },
    {
      "id": "hotel-unavailable",
      "page": 22,
      "title": "호텔 객실 문의 · 빈방 없음",
      "questions": [
        "I’d like to give you a situation and ask you to act it out. You have arrived in a new city and you’re trying to find a hotel for tonight. Go to the reception desk of a hotel. Describe the room you want and ask three or four questions to get information about what is available.",
        "I’m sorry, but there is a problem which I need you to resolve. You’ve learned that there are no rooms available in this hotel. Call your travel companions to let them know about the situation. Leave a message to describe the situation and propose alternative solutions to the problem.",
        "That’s the end of the situation. Think about a time when your travel plans did not work out as expected. What happened? Tell me all about the circumstances and what you and the others did. How was the situation finally resolved?"
      ],
      "stages": []
    },
    {
      "id": "business-trip",
      "page": 23,
      "title": "출장 호텔 문의 · 출장 취소",
      "questions": [
        "I’d like to give you a situation and ask you to act it out. You are going on a trip on business to another country. Call a hotel that you want to stay at and ask three or four questions about the hotel.",
        "I’m sorry, but there is a problem which I need you to resolve. You were supposed to go on a business trip to another country with your boss. However, something came up suddenly and you can’t go. Call your boss and explain the situation. And then, make two or three suggestions that will help you continue your business with the company overseas.",
        "That’s the end of the situation. Have you ever had a problem during a trip you took on business or for leisure? What was the nature of the problem and how did you deal with the situation? Describe in detail about what happened."
      ],
      "stages": [
        "질문하기 · PDF 22쪽",
        "문제 해결하기",
        "관련 경험"
      ]
    },
    {
      "id": "furniture",
      "page": 23,
      "title": "가구 구매 · 배송 문제",
      "questions": [
        "I’d like to give you a situation and ask you to act it out. You want to buy a new piece of furniture for your home. Speak to the store clerk and describe what you want. Ask three or four questions about the furniture they have for sale.",
        "I’m sorry, but there is a problem which I need you to resolve. When you get your new furniture at your home, you realize that there is a serious problem. Call the store and explain the problem in detail. Then, make some suggestions as to how you can resolve the problem as quickly as possible.",
        "That’s the end of the situation. Have you ever bought furniture that wasn’t what you had expected? Maybe you got the wrong color or maybe it didn’t fit in the space you had for it. Tell me about a time when you had a problem with a new piece of furniture."
      ],
      "stages": []
    },
    {
      "id": "real-estate",
      "page": 23,
      "title": "집 구하기 · 창문 파손",
      "questions": [
        "I’d like to give you a situation and ask you to act it out. You are looking for a new home. Call a real estate agent and introduce yourself. And then, ask three or four questions about homes and services they offer.",
        "I’m sorry, but there is a problem which I need you to resolve. When you get to your new home, you discover that a window is broken. Call the repair shop and leave a message. Describe in detail the condition of the window. Explain how you think the window got broken. Give two or three reasons why it is important that the window is fixed today.",
        "That’s the end of the situation. Tell me about a time when you found something that was broken. Why did the thing break and how did you deal with the situation? Give me all the details about that incident."
      ],
      "stages": [
        "질문하기",
        "문제 해결하기",
        "관련 경험 · PDF 24쪽"
      ]
    },
    {
      "id": "recycling-party",
      "page": 24,
      "title": "파티 후 쓰레기 · 이웃 불만",
      "questions": [
        "I’m sorry, but there is a problem which I need you to resolve. You often host large parties and take out most of the recycling and garbage the next day. However, other residents in your building are not happy about it, and one of them has come to complain to you. Explain the situation and offer some suggestions to resolve the problem.",
        "That’s the end of the situation. Describe a specific time in which you had trouble with recycling. It may have been a situation in which you moved to a new place and did not know the rules, or you put the materials in the wrong containers. Describe what happened from beginning to end."
      ],
      "stages": [
        "문제 해결하기",
        "관련 경험"
      ]
    },
    {
      "id": "bank",
      "page": 24,
      "title": "계좌 개설 · 카드 문제",
      "questions": [
        "I’d like to give you a situation and ask you to act it out. You need to open a new bank account. Call the bank and ask the teller three to four questions about opening a new account.",
        "I’m sorry, but there is a problem which I need you to resolve. You just got your credit card, but found out that there is something wrong with it. Call the bank, explain the situation and solve the problem.",
        "That’s the end of the situation. Have you ever had any problems with your bank card when you were using banking machines or ATMs? Describe the problem you had in detail."
      ],
      "stages": []
    },
    {
      "id": "gathering",
      "page": 24,
      "title": "주말 약속 문의",
      "questions": [
        "I’d like to give you a situation and ask you to act it out. You want to meet up with your friend on the weekend. Call your friend and ask two or three questions about what you can do together and when you want to meet."
      ],
      "stages": [
        "질문하기"
      ]
    }
  ]
};
