import fs from 'node:fs';
import vm from 'node:vm';
import {additions,reviews,roleplaySets,pageAudit} from '../scan-source.mjs';
import {decisions} from '../scan-decisions.mjs';

const ctx={window:{}};
for(const file of ['mock-data.js','mock-data-extra.js','practice-answers.js','shared-scripts.js','course-data.js','course-layout.js','course-sync.js'])vm.runInNewContext(fs.readFileSync(file,'utf8'),ctx);
const html=fs.readFileSync('index.html','utf8');
vm.runInNewContext('this.prompts='+html.match(/const prompts=(\[[\s\S]*?\n\]);/)[1],ctx);
const course=ctx.window.OPIC_COURSE;
function current(ref){
  if(ref.startsWith('L')){const part=course.lessons.find(p=>Number(p.id.split('-')[1])===Number(ref.slice(1)));return {title:part.title,text:part.english||part.text,url:'#/course/'+part.id};}
  if(ref.startsWith('M')){const [exam,num]=ref.slice(1).split('-').map(Number);const item=ctx.window.OPIC_MOCK_EXAMS.find(e=>e.id==='mock-'+exam).questions.find(q=>q.number===num);return {title:`모의고사 ${exam}회 ${num}번`,text:item.answer,url:'#/mock/mock-'+exam+'/'+num};}
  const i=Number(ref.slice(1))-1,prompt=ctx.prompts[i],answer=ctx.window.OPIC_PRACTICE_ANSWERS[i];
  let text=answer;
  if(typeof answer==='object'){const exam=ctx.window.OPIC_MOCK_EXAMS.find(e=>e.id===answer.exam);text=exam?.questions.find(q=>q.number===answer.number)?.answer||JSON.stringify(answer);}
  return {title:`실전 연습 ${i+1}번 · ${prompt.tag}`,text,url:'#/practice'};
}
// Only the selected whole answers enter application data; alternatives stay in the report.
const accepted=structuredClone(additions);
const existingExpressions=course.lessons.map(p=>p.text.toLowerCase()).join('\n');
const expressions=accepted.find(p=>p.kind==='expressions');
expressions.text=expressions.text.split('\n').filter(line=>!existingExpressions.includes(line.split(' → ')[0].toLowerCase())).join('\n');
const selections=decisions.filter(d=>d.choice==='textbook'||d.id==='hotel-booking').map((d,index)=>{
  const r=reviews.find(r=>r.id===d.id),paragraphs=r.text.split('\n\n');
  const hasQuestion=['concert-stage','house-repair','hiking-injury','hotel-problem','hotel-experience'].includes(d.id);
  const questions=hasQuestion?[paragraphs[0]]:d.target?ctx.window.OPIC_COURSE_PRACTICE.filter(p=>p.lessonId==='lesson-'+d.target).map(p=>p.en):d.mocks?.length?[ctx.window.OPIC_MOCK_EXAMS.find(e=>e.id==='mock-'+d.mocks[0][0]).questions.find(q=>q.number===d.mocks[0][1]).question]:[];
  const text=d.id==='hotel-booking'?current('P13').text:hasQuestion?paragraphs.slice(1).join('\n\n'):d.id==='recliner'?paragraphs[0]:r.text;
  if(d.id==='hotel-booking')questions.push(ctx.prompts[12].en);
  return {...d,page:d.choice==='textbook'?r.page:undefined,title:r.title,number:d.target||3001+index,questions,text,kind:'script',opening:d.id==='recliner'?paragraphs[1]:undefined};
});
fs.writeFileSync('scan-data.js','// Generated by scripts/build-scan.mjs from visually reviewed source.\nwindow.OPIC_SCAN = '+JSON.stringify({additions:accepted,roleplaySets,selections},null,2)+';\n');
fs.mkdirSync('docs',{recursive:true});
const lines=['# 교재스캔 · 스크립트 선택 결과','',`18개 대조 완료: 현재 버전 7개 유지, 교재 버전 11개 채택. 같은 구조는 질문 적합성과 문장 완성도로 판단하고, 다른 내용은 교재를 채택했습니다. 두 답변을 혼합하지 않았습니다.`,
  '','아래 원문 비교의 “현재 앱”은 변경 전 075db94 기준 보관 기록입니다. 실제 적용 범위와 예외는 각 선택 이유에 명시했습니다. 교재의 빈칸·대체 표현은 원문대로 유지합니다.',''];
for(const entry of reviews){
  const decision=decisions.find(d=>d.id===entry.id);
  lines.push(`## ${entry.id} · ${entry.title}`,'',`PDF ${entry.page}쪽 / 인쇄 ${entry.page+17}쪽`,'',entry.difference,'',`선택: **${decision.choice==='textbook'?'교재 사용':'현재 유지'}** — ${decision.reason}`,'','<details><summary>변경 전 앱·교재 원문 비교</summary>','');
  const seen=new Set();
  for(const ref of entry.refs){const item=current(ref);if(seen.has(item.text)){lines.push(`같은 현재 답변: ${ref} · ${item.title}`,'');continue;}seen.add(item.text);lines.push(`### 현재 앱 · ${ref} · ${item.title}`,'',item.text,'');}
  lines.push('### 교재','',entry.text,'','</details>','');
}
fs.writeFileSync('docs/교재스캔-차이점-검토.md',lines.join('\n'));
fs.writeFileSync('docs/교재스캔-반영내역.md',[
  '# 교재스캔 반영·대조 기록','',
  'PDF 24쪽을 이미지로 렌더링하여 전체 확인했습니다. PDF 쪽수와 인쇄 쪽수는 17쪽 차이가 납니다. 본문은 대부분 명확하게 읽혔으며 추측으로 복원한 단어는 없습니다. 읽히지 않는 긴 필기는 제외했습니다. 워터마크·쪽수·반복 머리말은 학습 본문에서 제외했습니다.',
  '', '18개 차이점을 개별 검토하여 7개는 현재 버전, 11개는 교재 버전을 채택했습니다. 선택한 답변은 학습·모의고사·실전 연습에 반영했습니다. 질문 자체가 다른 국내 장소 묘사·국가 비교·직무 교육·여행 취소는 별도 자료로 유지합니다. 원본 종합정리 파일은 보존하고 선택 결과를 앱에서 우선 적용합니다. 상세 이유는 교재스캔-차이점-검토.md에 기록했습니다.',
  '', '## 쪽별 처리','', '| PDF / 인쇄 | 내용 | 최초 판독 기록 | 최종 선택 |','|---|---|---|---|',
  ...pageAudit.map(([p,title,note])=>`| ${p} / ${p+17} | ${title} | ${note} | ${reviews.filter(r=>r.page===p).map(r=>r.title+': '+(decisions.find(d=>d.id===r.id).choice==='textbook'?'교재 반영':'현재 유지')).join(' / ')||'추가 자료 유지'} |`),
  '', '## 추가 자료','',...accepted.map(e=>`- PDF ${e.page}쪽 · ${e.title} → ${e.section}${e.target?' · 기존 질문에 보완':''}`),
  '', '## 추가 롤플레이 묶음','',...roleplaySets.map(e=>`- PDF ${e.page}쪽 · ${e.title} (${e.questions.length}문제)`),
  '', '## 표기 원칙','',
  '- 인쇄된 form, United Stated, three of four, on item, tell me salesperson 등은 읽기 실패가 아니라 원문에 보이는 표기입니다. 자동으로 교정하지 않았습니다.',
  '- 문장 틀의 점선 길이는 `...`로 통일했습니다. 문장을 완성하기 위한 인물·장소·사건을 추가하지 않았습니다.',
  '- 2쪽의 영어 필기 조각은 별도 문장 구성 참고로만 표시합니다. 4쪽·11쪽 등의 불명확한 긴 필기는 보완하지 않았습니다.',
  '- 기존 자료와 같은 의미의 질문은 반복 수록하지 않았습니다. 다만 문장 틀을 적용하는 질문이나 추가 조건이 있는 질문은 함께 읽을 수 있게 유지했습니다.',
  '- 선택한 교재 답변만 활성 자료에 반영하며, 채택하지 않은 대안은 비교 문서에만 보관합니다. 호텔은 질문하기·문제 해결·관련 경험을 한 화면에서 학습합니다.',''
].join('\n'));
console.log(`Built ${accepted.length} additions, ${roleplaySets.length} roleplay sets; ${reviews.length} comparisons, ${pageAudit.length} pages audited.`);
