import fs from 'node:fs';
import vm from 'node:vm';
import {additions,reviews,roleplaySets,pageAudit} from '../scan-source.mjs';

const ctx={window:{}};
for(const file of ['mock-data.js','mock-data-extra.js','practice-answers.js','shared-scripts.js','course-data.js','course-layout.js','course-sync.js'])vm.runInNewContext(fs.readFileSync(file,'utf8'),ctx);
const html=fs.readFileSync('index.html','utf8');
vm.runInNewContext('this.prompts='+html.match(/const prompts=(\[[\s\S]*?\n\]);/)[1],ctx);
const course=ctx.window.OPIC_COURSE;
function current(ref){
  if(ref.startsWith('L')){const part=course.lessons.find(p=>Number(p.id.split('-')[1])===Number(ref.slice(1)));return {title:part.title,text:part.english||part.text,url:'#/course/'+part.id};}
  if(ref.startsWith('M')){const [exam,num]=ref.slice(1).split('-').map(Number);const item=ctx.window.OPIC_MOCK_EXAMS.find(e=>e.id==='mock-'+exam).questions.find(q=>q.number===num);return {title:`모의고사 ${exam}회 ${num}번`,text:item.answer,url:'#/mock/mock-'+exam+'/'+num};}
  const i=Number(ref.slice(1))-1,prompt=ctx.prompts[i],answer=ctx.window.OPIC_PRACTICE_ANSWERS[i];
  let text=answer;
  if(typeof answer==='object'){const exam=ctx.window.OPIC_MOCK_EXAMS.find(e=>e.id===answer.examId);text=exam?.questions.find(q=>q.number===answer.questionNumber)?.answer||JSON.stringify(answer);}
  return {title:`실전 연습 ${i+1}번 · ${prompt.tag}`,text,url:'#/practice'};
}
// Keep the full source comparison out of the application data until the user selects it.
const accepted=structuredClone(additions);
const existingExpressions=course.lessons.map(p=>p.text.toLowerCase()).join('\n');
const expressions=accepted.find(p=>p.kind==='expressions');
expressions.text=expressions.text.split('\n').filter(line=>!existingExpressions.includes(line.split(' → ')[0].toLowerCase())).join('\n');
fs.writeFileSync('scan-data.js','// Generated by scripts/build-scan.mjs from visually reviewed source.\nwindow.OPIC_SCAN = '+JSON.stringify({additions:accepted,roleplaySets},null,2)+';\n');
fs.mkdirSync('docs',{recursive:true});
const lines=['# 교재스캔 · 기존 앱과 다른 내용','',`기준: 앱 커밋 075db94, 교재스캔.pdf 전체 24쪽(인쇄 18~41쪽). 아래 ${reviews.length}개 항목은 앱에 적용하지 않았습니다.`,
  '','각 항목의 **현재 앱**과 **교재**를 비교해 선택할 수 있습니다. 교재의 문법·철자·빈칸은 임의로 고치지 않았으며, 슬래시로 병기된 대체 표현도 유지했습니다.',
  '','선택은 항목 ID와 함께 “현재 유지 / 교재 사용 / 둘 다 별도 예문으로 유지”로 알려주시면 됩니다.',''];
for(const entry of reviews){
  lines.push(`## ${entry.id} · ${entry.title}`,'',`PDF ${entry.page}쪽 / 인쇄 ${entry.page+17}쪽`,'',entry.difference,'','선택: 미정','','<details><summary>현재 앱·교재 원문 비교</summary>','');
  const seen=new Set();
  for(const ref of entry.refs){const item=current(ref);if(seen.has(item.text)){lines.push(`같은 현재 답변: ${ref} · ${item.title}`,'');continue;}seen.add(item.text);lines.push(`### 현재 앱 · ${ref} · ${item.title}`,'',item.text,'');}
  lines.push('### 교재','',entry.text,'','</details>','');
}
fs.writeFileSync('docs/교재스캔-차이점-검토.md',lines.join('\n'));
fs.writeFileSync('docs/교재스캔-반영내역.md',[
  '# 교재스캔 반영·대조 기록','',
  'PDF 24쪽을 이미지로 렌더링하여 전체 확인했습니다. PDF 쪽수와 인쇄 쪽수는 17쪽 차이가 납니다. 본문은 대부분 명확하게 읽혔으며 추측으로 복원한 단어는 없습니다. 읽히지 않는 긴 필기는 제외했습니다. 워터마크·쪽수·반복 머리말은 학습 본문에서 제외했습니다.',
  '', '기존 종합정리와 답변은 교체하지 않았습니다. 기존 질문만 있는 사물 항목에 실제 교재 답변을 보완하고, 영문 시작 문장만 있는 경우 시작 문장만 넣었습니다. 교재의 빈칸은 문장 틀로 유지하며 완성 답변으로 제시하지 않습니다. 실전 연습의 기존 답변과 다른 교재 예문은 차이점 문서에만 보관했습니다.',
  '', '## 쪽별 처리','', '| PDF / 인쇄 | 내용 | 처리 |','|---|---|---|',
  ...pageAudit.map(([p,title,note])=>`| ${p} / ${p+17} | ${title} | ${note} |`),
  '', '## 추가 자료','',...accepted.map(e=>`- PDF ${e.page}쪽 · ${e.title} → ${e.section}${e.target?' · 기존 질문에 보완':''}`),
  '', '## 추가 롤플레이 묶음','',...roleplaySets.map(e=>`- PDF ${e.page}쪽 · ${e.title} (${e.questions.length}문제)`),
  '', '## 표기 원칙','',
  '- 인쇄된 form, United Stated, three of four, on item, tell me salesperson 등은 읽기 실패가 아니라 원문에 보이는 표기입니다. 자동으로 교정하지 않았습니다.',
  '- 문장 틀의 점선 길이는 `...`로 통일했습니다. 문장을 완성하기 위한 인물·장소·사건을 추가하지 않았습니다.',
  '- 2쪽의 영어 필기 조각은 별도 문장 구성 참고로만 표시합니다. 4쪽·11쪽 등의 불명확한 긴 필기는 보완하지 않았습니다.',
  '- 기존 자료와 같은 의미의 질문은 반복 수록하지 않았습니다. 다만 문장 틀을 적용하는 질문이나 추가 조건이 있는 질문은 함께 읽을 수 있게 유지했습니다.',
  '- 검토 대기 스크립트는 검색·템플릿·말하기 연습 등 앱의 활성 자료에 포함하지 않습니다.',''
].join('\n'));
console.log(`Built ${accepted.length} additions, ${roleplaySets.length} roleplay sets; ${reviews.length} comparisons, ${pageAudit.length} pages audited.`);
